### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by dillfrescott** [nilsherzig/LLocalSearch#1]
This is strictly opinionated but I think you should only put 2 or 3 sample prompts on the page. And make them a bit less controversial than some of the ones that are on there.

Let me know what you think

**Comment by nilsherzig** [comment]
Yea, you're right, I was just trying to test some model censorship with these prompts, since a mayor benefit of local llms is that they can be uncensored. 

Any interesting prompt examples you would like to see on there?

**Comment by dillfrescott** [comment]
Ahh gotcha gotcha. I'd put just some basic neutral ones in there and the user can edit the file and add whatever they want if they want to change it!

**Comment by nilsherzig** [comment]
Ah true, I should expose this as an admin setting, thanks :)

(Sorry for editing your comment, i was just surprised that I'm allowed to do that)

**Comment by dillfrescott** [comment]
Oh I didn't even notice haha
