### ISSUE TITLE
[FEATURE] Option to select a chat model from the UI

### ISSUE THREAD

**Issue by PieBru** [nilsherzig/LLocalSearch#11]
Hi Nils,
that's much like Open-WebUI already does, It may be useful to select a different mode, a specialized one, or a different quant model without restarting the app.
Thank you,
Piero

**Comment by nilsherzig** [comment]
I think I should open some kind of infrastructure planing thread. 

With the introduction of "chat mode" I think there is a nice way to handle the expert LLM thing. 

What are your thoughts on this:

We have a "chat layer" which has a history of the user's prompts and messages (green and purple). If needed, this chat chain can call other chains, which run autonomous without user interaction by using a self critique loop.

It would be very easy to add more chains to this, like a "programming chain" using deepseek-coder as the LLM. 

I would have to come up with a config format for these chains, but essentially they are just a couple of conditions and strings in / strings out.

In the meantime, I can add a simple HTML select for the models loaded on the user's ollama instance. The only problem with this is, that different llms need different parameters and prompts, which currently aren't configurable through the webui.

![infra drawio](https://github.com/nilsherzig/LLocalSearch/assets/72463901/09f8a99b-837e-453e-84b4-4b08e0bccaae)

**Comment by nilsherzig** [comment]
![image](https://github.com/nilsherzig/LLocalSearch/assets/72463901/557d2f35-3389-4ab5-aaf1-dd73d43cedbb)

![image](https://github.com/nilsherzig/LLocalSearch/assets/72463901/3a8cb6de-1f8a-4dc7-ba78-c46aa8a3e433)


Working on a model switch popup
