### ISSUE TITLE
nichts funktioniert. müll.

### ISSUE THREAD

**Issue by NeverBeLazyG** [nilsherzig/LLocalSearch#121]
ich möchte einmal erleben dass ein entwickler mal seine veröffentlichungen selber testet bevor er sie freigibt. es nervt nur noch dieses ewige gefrickel bei jedem git projekt.

man befolgt die anleitung. 

und dann gibt es zu 95% irgend einen fehler, den man dann stundenlang beheben muss. leute ihr nervt nur noch. lasst es sein, wenn ihr es nicht könnt.

einfach nur peinlich.

alter teste doch mal dein tool in einer frischen umgebung, um zu schauen, ob deine lächerliche anleitung überhaupt funktioniert. vergeude nicht die zeit der leute mit rumfrickeln und fehlersuche.

ich wünsche mir echt die guten alten zeiten zurück, wo man setup.exe anclicken konnte und es lief anschliessend. 

euer mist nervt nur noch. tausend abhängigkeiten, und nicht mal die docker container funktionieren. alles schrott.

**Comment by nilsherzig** [comment]
https://www.urbandictionary.com/define.php?term=skill%20issue

Gebe dir allerdings recht, dass das ganze recht kompliziert ist. Die Menge an Teilen lässt sich nicht reduzieren, da mein Projekt nunmal auf SearXNG und ähnliches angewiesen ist. Der setup Prozess ist allerdings wirklich scheiße, gebe ich gerne zu. Aber so ist das nunmal, wenn man neben seinem Studium und Arbeit noch an irgendwas rumhackt. Kannst mich ja vollzeit bezahlen und im Tausch gibts ne binary mit idoten sicherem multi step setup.

**Comment by NeverBeLazyG** [comment]
> Aber danke jedenfalls dafür, dass du das Issue direkt in mehreren Sprachen aufgemacht hast, musst ja echt frustriert gewesen sein haha

ja, nach ca. 20 ai tools die ich bei github getestet habe, und bei denen ich fast bei allen rumfrickeln musste bis es mal lief, war dein, das das fass zum überlaufen gebracht hat. sorry. aber github nervt langsam. ich bin echt zu alt mittlerweile für dieses gefrickle. ich mache diese IT sch***e seit 25 jahren. mein hirn hat keine lust mehr zum frickeln.
