### ISSUE TITLE
Parsing errors

### ISSUE THREAD

**Issue by dillfrescott** [nilsherzig/LLocalSearch#14]
![Screenshot_20240402_035733](https://github.com/nilsherzig/LLocalSearch/assets/56714680/7cc0b01f-5491-4fd7-8e31-a33037cb1791)

This happens in an endless loop until the tab is closed after you ask it a question..

**Comment by nilsherzig** [comment]
Im going to add #15 today, which will make bug reports a lot more informative and before adding anything else i will create a "stable" release system (propably without the chat feature in v0.1) to reduce problems like this one. 

In the meantime, please check that you're using the latest version. Using the chat format requires a different "final message" prompt format. 

https://github.com/nilsherzig/LLocalSearch/blob/de2d4da828170ace4f4df2bcd00e30c0462217d0/backend/utils/prompts.go#L5-L7

The llm had to write "Final Message" before, now its just "AI:".

**Comment by nilsherzig** [comment]
Im back at university and working after this weekend, which limits the time i can spend on the project per day. 

I will try my best to polish the existing experiance before adding new features :). I think i should have keept the chat thing on a different branch haha.

**Comment by dillfrescott** [comment]
Oh okay! No problem!

**Comment by nilsherzig** [comment]
![image](https://github.com/nilsherzig/LLocalSearch/assets/72463901/9c728f9f-13e3-437b-a211-5675c1334146)

btw works for me on the current commit

**Comment by nilsherzig** [comment]
It feels like small llms (around 7b) have a hard time performing consistent even with the same settings and low temps

**Comment by dillfrescott** [comment]
ah, gotcha. I'll try a larger model when I get a chance.

**Comment by nilsherzig** [comment]
I (can) only use the hermes-2-pro 7b thing, so it's definitely my / a priority of this repo to work with small models. They can work very well, but i sometimes they just miss the point despite being run with the same exact settings haha
