### ISSUE TITLE
An option to just output final message?

### ISSUE THREAD

**Issue by dillfrescott** [nilsherzig/LLocalSearch#2]
This would be nice, maybe have it pop up the chain messages fleetingly similar to when microsoft copilot searches for things, then just display the final answer.

**Comment by nilsherzig** [comment]
Yes, this should definitely be an option. What do you think of something like this? Separating the chain log from the final message while preserving a way for the user to check what's going on 

![image](https://github.com/nilsherzig/LLocalSearch/assets/72463901/d16d0638-ab92-4ba0-8ff9-79b779d1836c)

I just woke up, but i think this will be the first thing i implement today haha

**Comment by nilsherzig** [comment]
![Screenshot_20240330-083539](https://github.com/nilsherzig/LLocalSearch/assets/72463901/0167aaec-1644-43b4-9f9d-475dbe5687d3)


I also like the idea of collapsing log messages by default like this

**Comment by nilsherzig** [comment]
https://github.com/nilsherzig/LLocalSearch/assets/72463901/177e9760-4378-4317-b214-44775e7d3f0e

hi, I added a log toggle :)

I'm still going to implement a better way to display logs (collapsing them and their children) but hopefully this will serve as a workable hotfix

**Comment by dillfrescott** [comment]
That looks excellent! :)

**Comment by nilsherzig** [comment]
Thanks :)
