### ISSUE TITLE
😒Model all-minilm:v2 does not exist

### ISSUE THREAD

**Issue by Claudioappassionato** [nilsherzig/LLocalSearch#20]
I've tried everything and I don't know what to do anymore - I always get this error : Model all-minilm:v2 does not exist and could not be pulled: Post "http://192.168.0.109:11434/api/pull": dial tcp 192.168.0.109:11434: connect: connection refused

**Comment by nilsherzig** [comment]
Are you sure that your ollama instance runs on this IP and port?

**Comment by eduardvercaemer** [comment]
Just so you dont make the same mistake as me (not used to using docker). Docker won't automagically connect that ip to your localhost 🤦🏼

**Comment by sammcj** [comment]
For me I already was hosting ollama with OLLAMA_HOST=0.0.0.0, I still had to manually pull all-minilm:v2 for the app to work so I think there's still something up.

**Comment by texuf** [comment]
I changed this hard coded string in llm_backends.go to include the v2 suffix and it worked
```

func NewOllamaEmbeddingLLM() (*ollama.LLM, error) {
	modelName := "all-minilm:v2" // <-- add "v2"
	return NewOllama(modelName)
}
```

**Comment by sammcj** [comment]
ohh, good spotting, PR submitted - https://github.com/nilsherzig/LLocalSearch/pull/25

**Comment by nilsherzig** [comment]
> I changed this hard coded string in llm_backends.go to include the v2 suffix and it worked
> ```
> 
> func NewOllamaEmbeddingLLM() (*ollama.LLM, error) {
> 	modelName := "all-minilm:v2" // <-- add "v2"
> 	return NewOllama(modelName)
> }
> ```

Ah fuck, im so sorry for that :/

I really need some e2e tests for this project, its so easy to muss something like that. Thanks :)

**Comment by microspino** [comment]
@nilsherzig you're pretty damn wonderful!
stuck into this, 1 hour, pull...Back in business. 🤟
THX @sammcj  @texuf  @eduardvercaemer @Claudioappassionato

**Comment by sammcj** [comment]
Yeah that’s an amazing response! Thanks so much. Awesome project!

**Comment by nilsherzig** [comment]
> > @nilsherzigsei dannatamente meraviglioso! bloccato in questo, 1 ora, tira... Torna in affari. 🤟 GRAZIE@sammcj @texuf @eduardvercaemer @Claudioappassionato
> 
> sorry but how can I understand exactly what my OLLAMA IP is? in my docker I found this: Resources Network Configure the way Docker containers interact with the network
> 
> 192.168.65.0/24 Docker subnet default: 192.168.65.0/24

i changed a lot of configs to more reasonable defaults since your first comment. Could you try pulling the repo again and check if it works by now? Good chance your problem got resolved :)

**Comment by Claudioappassionato** [comment]
> > > @nilsherzigsei dannatamente meraviglioso! bloccato in questo, 1 ora, tira... Torna in affari. 🤟 GRAZIE@sammcj@texuf @eduardvercaemer @Claudioappassionato
> > 
> > 
> > scusate ma come faccio a capire esattamente qual'è il mio IP OLLAMA? nella mia finestra mobile ho trovato questo: Risorse Rete Configura il modo in cui i contenitori Docker interagiscono con la rete
> > 192.168.65.0/24 Impostazione predefinita della sottorete Docker: 192.168.65.0/24
> 
> ho cambiato molte configurazioni con valori predefiniti più ragionevoli dal tuo primo commento. Potresti provare a estrarre di nuovo il repository e verificare se funziona adesso? Ci sono buone probabilità che il tuo problema sia stato risolto :)

Sorry but I'm not very good with codes. I try to do my best. But if you explain to me step by step what I need to change, you'll make me happy

**Comment by nilsherzig** [comment]
try deleting the whole project from your pc and running the tutorial / setup steps again :)

**Comment by Claudioappassionato** [comment]
> 2\. OLLAMA_HOST=0.0.0.0 ollama serve

👎

**Comment by CL0R0X** [comment]
I am still having this issue, even with the updated code. I don't know what to change or add. 
<img width="700" alt="Screenshot 2024-04-04 at 9 58 06 PM" src="https://github.com/nilsherzig/LLocalSearch/assets/94938596/12381c1f-0e1a-42a8-bd6b-6fc97318e0d2">

**Comment by nilsherzig** [comment]
You dont have to censor 192.*.*.* ips, those are local ones behind your router. Please show me your ollama start command, i assume you're not listening on the right interface

**Comment by CL0R0X** [comment]
Is this what you are looking for:
<img width="764" alt="Screenshot 2024-04-05 at 9 34 06 AM" src="https://github.com/nilsherzig/LLocalSearch/assets/94938596/c7361429-5e74-44c5-b863-c01f5a546651">
or this
<img width="764" alt="Screenshot 2024-04-05 at 9 42 25 AM" src="https://github.com/nilsherzig/LLocalSearch/assets/94938596/9a4afd26-8e96-4210-9767-b49cb29228e3">

**Comment by Claudioappassionato** [comment]
> È questo quello che cerchi: oppure questo <img alt="Schermata del 05-04-2024 alle 9:34:06" width="764" src="https://private-user-images.githubusercontent.com/94938596/320039766-c7361429-5e74-44c5-b863-c01f5a546651.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjg1OTMsIm5iZiI6MTcxMjMyODI5MywicGF0aCI6Ii85NDkzODU5Ni8zMjAwMzk3NjYtYzczNjE0MjktNWU3NC00NGM1LWI4NjMtYzAxZjVhNTQ2NjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE0NDQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMTk0M2JjYTBlNjNmZWZkMjE4MTRlYTAwMDlkZDMzMjI5ZThmZjA5ZjRiMmU3MzQzY2JjMTQ4NWEyMWY5NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8echWylM1TeFkid05MifyDe1Y_n31GgtP9Lm5igRKvQ"> <img alt="Schermata del 05-04-2024 alle 9:42:25" width="764" src="https://private-user-images.githubusercontent.com/94938596/320040105-9a4afd26-8e96-4210-9767-b49cb29228e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjg1OTMsIm5iZiI6MTcxMjMyODI5MywicGF0aCI6Ii85NDkzODU5Ni8zMjAwNDAxMDUtOWE0YWZkMjYtOGU5Ni00MjEwLTk3NjctYjQ5Y2IyOTIyOGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE0NDQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ODg3NjE0MzcyODI5ODQ5NTU4Mzg3ZTU4MmMyZDg4ZmJlN2EyYmRlMTZjODA4OWUzZmRjZGVjN2Y5NTgwMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C63siIT_RJ7ldnJqMMiveG3D7y6ZlGJTpV_wH75CykQ">
can you put the images in text format? 
😊💕

**Comment by CL0R0X** [comment]
Oh sorry, I felt like images are just descriptors. 
```
package utils

import (
	"context"
	"fmt"
	"log/slog"
	"os"

	"github.com/google/uuid"
	"github.com/ollama/ollama/api"
	"github.com/tmc/langchaingo/llms/ollama"
)

func NewOllamaEmbeddingLLM() (*ollama.LLM, error) {
	modelName := "all-minilm:v2"
	return NewOllama(modelName)
}

func NewOllama(modelName string) (*ollama.LLM, error) {
	return ollama.New(ollama.WithModel(modelName), ollama.WithServerURL(os.Getenv("OLLAMA_HOST")), ollama.WithRunnerNumCtx(16000))
}
```

This is part of the yaml dev file:
````
services:
  backend:
    volumes:
      - ./backend/:/app/
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST:-http://host.docker.internal:11434}
      - CHROMA_DB_URL=${CHROMA_DB_URL:-http://chromadb:8000}
      - SEARXNG_DOMAIN=${SEARXNG_DOMAIN:-http://searxng:8080}
      - MAX_ITERATIONS=${MAX_ITERATIONS:-30}
    networks:
      - llm_network_dev

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app/
    ports:
      - '3000:5173'
    networks:
      - llm_network_dev

  chromadb:
    image: chromadb/chroma
    networks:
      - llm_network_dev
    # attach: false
    # logging:
    #   driver: none
```

**Comment by Claudioappassionato** [comment]
> Oh sorry, I felt like images are just good descriptors.
> 
> ```
> package utils
> 
> import (
> 	"context"
> 	"fmt"
> 	"log/slog"
> 	"os"
> 
> 	"github.com/google/uuid"
> 	"github.com/ollama/ollama/api"
> 	"github.com/tmc/langchaingo/llms/ollama"
> )
> 
> func NewOllamaEmbeddingLLM() (*ollama.LLM, error) {
> 	modelName := "all-minilm:v2"
> 	return NewOllama(modelName)
> }
> 
> func NewOllama(modelName string) (*ollama.LLM, error) {
> 	return ollama.New(ollama.WithModel(modelName), ollama.WithServerURL(os.Getenv("OLLAMA_HOST")), ollama.WithRunnerNumCtx(16000))
> }
> ```
> 
> This is part of the yaml dev file:
> 
> ```
> services:
>   backend:
>     volumes:
>       - ./backend/:/app/
>     build:
>       context: ./backend
>       dockerfile: Dockerfile.dev
>     environment:
>       - OLLAMA_HOST=${OLLAMA_HOST:-http://host.docker.internal:11434}
>       - CHROMA_DB_URL=${CHROMA_DB_URL:-http://chromadb:8000}
>       - SEARXNG_DOMAIN=${SEARXNG_DOMAIN:-http://searxng:8080}
>       - MAX_ITERATIONS=${MAX_ITERATIONS:-30}
>     networks:
>       - llm_network_dev
> 
>   frontend:
>     depends_on:
>       - backend
>     build:
>       context: .
>       dockerfile: Dockerfile.dev
>     volumes:
>       - ./:/app/
>     ports:
>       - '3000:5173'
>     networks:
>       - llm_network_dev
> 
>   chromadb:
>     image: chromadb/chroma
>     networks:
>       - llm_network_dev
>     # attach: false
>     # logging:
>     #   driver: none
> ```
> ```

thanks :-). Maybe a silly question since I can't get the server to work. But do you have to download the minilm locally?

**Comment by CL0R0X** [comment]
I don't think that's the issue of downloading miniLM because it is just a sentence transformer https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2

**Comment by CL0R0X** [comment]
I fixed the issue. To solve my issue I had to have Ollama actively running and a model had to be downloaded ahead of time. That made my solution work.

**Comment by CL0R0X** [comment]
Update 2:
It seems like the model is not responding at all:
![PNG image](https://github.com/nilsherzig/LLocalSearch/assets/94938596/7402c3ef-f547-4028-b55b-4e9acd90fd9a)
