### ISSUE TITLE
Redis docker: remove chown necessity?

### ISSUE THREAD

**Issue by Eidenz** [nilsherzig/LLocalSearch#33]
Hello, I run all my dockers in UNRAID, and the redis container forcing a chown command is preventing it from starting because UNRAID doesn't allow the use of chown or chmod, permissions are handled automatically or ahead, not by containers.

![image](https://github.com/nilsherzig/LLocalSearch/assets/27901016/68a71348-79e6-4ad4-b9a0-4c36551d5d88)
![image](https://github.com/nilsherzig/LLocalSearch/assets/27901016/1312bd05-a6ff-453c-babb-4446a7a76453)

Note: this doesn't prevent the app from starting though.

**Comment by nilsherzig** [comment]
Does search work? If so, I guess you could just run Redis without persistent storage as a quick fix. Caching search results (especially persistent over server restarts) isn't really needed if you're the only user.

**Comment by Eidenz** [comment]
Search worked yes, I just made this issue to warn containers may break on some systems if they use these commands

**Comment by nilsherzig** [comment]
It's a good issue, I just down know how to solve this, it's up to the redis developers I think. Are you could run the container as a user who has the rights to do this, but that's probably a big security issue.

**Comment by Eidenz** [comment]
Oh weird, I have other redis containers (I just didn't bother modifying the docker compose yet to use it), only this one has this error, so I thought you gave it some startup command or something.
