### ISSUE TITLE
minimal instructions on how to setup ollama for this project?

### ISSUE THREAD

**Issue by zaggynl** [nilsherzig/LLocalSearch#34]
I installed ollama, downloaded the all-minilm:v2 model as is mentioned in the error message from this project:
`
Model all-minilm:v2 does not exist and could not be pulled: Post "http://127.0.0.1:11434/api/pull": dial tcp 127.0.0.1:11434: connect: connection refused`

curl http://127.0.0.1:11434 shows:
Ollama is running

ollama list
NAME            ID              SIZE    MODIFIED       
all-minilm:v2   1b226e2802db    45 MB   11 minutes ago

**Comment by nilsherzig** [comment]
hi could you please try this as a domain? (just run git pull, to get the current configs).  

https://github.com/nilsherzig/LLocalSearch/blob/a422c14c94be5bbc7b7b9da56c3d155fd7e0d555/docker-compose.yaml#L7-L20

Localhost (127.0.0.1) on the container is not the localhost of your host system (where ollama is probably running)

**Comment by Trisert** [comment]
Hi, i'm having the same problem runnin in NixOS. I'm using the latest pull from the repo and the same docker-compose.yaml that use the the extra_hosts config but it seems to still not use the same localhost for docker. My docker-compose version is 2.23.1

**Comment by nilsherzig** [comment]
> Hi, i'm having the same problem runnin in NixOS. I'm using the latest pull from the repo and the same docker-compose.yaml that use the the extra_hosts config but it seems to still not use the same localhost for docker. My docker-compose version is 2.23.1

Is your ollama instance listening on the right network interface?

**Comment by Trisert** [comment]
> > Hi, i'm having the same problem runnin in NixOS. I'm using the latest pull from the repo and the same docker-compose.yaml that use the the extra_hosts config but it seems to still not use the same localhost for docker. My docker-compose version is 2.23.1
> 
> Is your ollama instance listening on the right network interface?

I've tried starting ollama by running `ollama serve` and also by `OLLAMA_HOST=0.0.0.0 ollama serve`. Since I have not used Ollama much it is likely that I am doing it wrong. If you can suggest where I might be going wrong in initializing the server I might try a different configuration.

**Comment by mike-luabase** [comment]
@kkokosa that fixed it for me

```
ollama pull all-minilm
```

**Comment by zaggynl** [comment]
> hi could you please try this as a domain? (just run git pull, to get the current configs).
> 
> https://github.com/nilsherzig/LLocalSearch/blob/a422c14c94be5bbc7b7b9da56c3d155fd7e0d555/docker-compose.yaml#L7-L20
> 
> Localhost (127.0.0.1) on the container is not the localhost of your host system (where ollama is probably running)

Thanks for the reply, I've tried both:

      - OLLAMA_HOST=http://host.docker.internal:11434
#       - OLLAMA_HOST=http://127.0.0.1:11434

OLLAMA_HOST=0.0.0.0 ollama serve
seems to have done the trick as a workaround, I'll add this to the systemd file

**Comment by nilsherzig** [comment]
> > hi could you please try this as a domain? (just run git pull, to get the current configs).
> > https://github.com/nilsherzig/LLocalSearch/blob/a422c14c94be5bbc7b7b9da56c3d155fd7e0d555/docker-compose.yaml#L7-L20
> > 
> > Localhost (127.0.0.1) on the container is not the localhost of your host system (where ollama is probably running)
> 
> Thanks for the reply, I've tried both:
> 
> ```
>       - OLLAMA_HOST=http://host.docker.internal:11434
> #       - OLLAMA_HOST=http://127.0.0.1:11434
> ```
> 
> OLLAMA_HOST=0.0.0.0 ollama serve seems to have done the trick as a workaround, I'll add this to the systemd file
> 
> /etc/systemd/system/ollama.service added Environment="OLLAMA_HOST=0.0.0.0" below: Environment="PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
> 
> sudo systemctl daemon-reload sudo service ollama restart

I think I should change the docker networking. The whole localhost story is a bit too confusing for people who run Ollama on the same machine.

**Comment by Jon-bioinfo** [comment]
Same problem? after `git pull; git checkout .; docker compose pull; curl http://localhost:11434` shows "Ollama is running"

`Model all-minilm:v2 does not exist and could not be pulled: Post "http://host.docker.internal:11434/api/pull": dial tcp 172.17.0.1:11434: connect: connection refused`

**Comment by blakkd** [comment]
> hi could you please try this as a domain? (just run git pull, to get the current configs).
> 
> https://github.com/nilsherzig/LLocalSearch/blob/a422c14c94be5bbc7b7b9da56c3d155fd7e0d555/docker-compose.yaml#L7-L20
> 
> Localhost (127.0.0.1) on the container is not the localhost of your host system (where ollama is probably running)

Saved me! I think this OLLAMA_HOST=http://host.docker.internal:11434 trick should be pinned somewhere cause I spent some times digging arround this.
