### ISSUE TITLE
Exiting chain with error: agent not finished before max iterations

### ISSUE THREAD

**Issue by andatt** [nilsherzig/LLocalSearch#4]
Hi,

Great job with this, just wondering where I can set the max iterations? Have had a look around in the config files I can see but can't find anything.

Thanks

**Comment by nilsherzig** [comment]
Oh, yea, you're right, it's currently hard coded.  I wasn't sure if I should expose this setting to the web interface, but I can definitely expose it to the expose file. 

cc #3

**Comment by nilsherzig** [comment]
it's now exposed via env vars in the compose file, I will keep this issue open as until I decided if I want to expose it to the webui
