### ISSUE TITLE
Exiting chain with error: model 'all-minilm' not found, try pulling it first

### ISSUE THREAD

**Issue by Claudioappassionato** [nilsherzig/LLocalSearch#40]
Exiting chain with error: model 'all-minilm' not found, try pulling it first

I WAIVER. Too many hours without a solution.
when you make a simple and functional project I will be happy

backend-1   | 2024/04/04 13:43:49 Error adding document: error adding document: model 'all-minilm' not found, try pulling it first
backend-1   | 2024/04/04 13:43:49 error from evaluator: Error adding document: error adding document: model 'all-minilm' not found, try pulling it first
backend-1   | 2024/04/04 13:43:49 Error adding document: error adding document: model 'all-minilm' not found, try pulling it first
backend-1   | 2024/04/04 13:43:49 error from evaluator: Error adding document: error adding document: model 'all-minilm' not found, try pulling it first

rst
backend-1   | 2024/04/04 13:43:27 INFO Creating new session session=9b2eea7b-c5eb-4662-908c-2435f77d3c75
backend-1   | 2024/04/04 13:43:27 INFO Starting agent chain session=9b2eea7b-c5eb-4662-908c-2435f77d3c75 userQuery="{Prompt:how much do OpenAI and Microsoft plan to spend on their new datacenter? MaxIterations:30 ModelName:knoopx/hermes-2-pro-mistral:7b-q8_0 Session:9b2eea7b-c5eb-4662-908c-2435f77d3c75}" startTime=2024-04-04T13:43:27.128Z
searxng-1   | 2024-04-04 13:43:48,208 WARNING:searx.engines.qwant: ErrorContext('searx/engines/qwant.py', 191, 'raise SearxEngineAPIException(f"{msg} ({error_code})")', 'searx.exceptions.SearxEngineAPIException', None, ('unknown (27)',)) False
searxng-1   | 2024-04-04 13:43:48,209 ERROR:searx.engines.qwant: exception : unknown (27)
searxng-1   | Traceback (most recent call last):
searxng-1   |   File "/usr/local/searxng/searx/search/processors/online.py", line 163, in search
searxng-1   |     search_results = self._search_basic(query, params)
searxng-1   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1   |   File "/usr/local/searxng/searx/search/processors/online.py", line 151, in _search_basic
searxng-1   |     return self.engine.response(response)
searxng-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1   |   File "/usr/local/searxng/searx/engines/qwant.py", line 151, in response
searxng-1   |     return parse_web_api(resp)
searxng-1   |            ^^^^^^^^^^^^^^^^^^^
searxng-1   |   File "/usr/local/searxng/searx/engines/qwant.py", line 191, in parse_web_api
searxng-1   |     raise SearxEngineAPIException(f"{msg} ({error_code})")
searxng-1   | searx.exceptions.SearxEngineAPIException: unknown (27)
backend-1   | 2024/04/04 13:43:49 Search found 44 Results
backend-1   | 2024/04/04 13:43:49 error from evaluator: no content found

**Comment by nilsherzig** [comment]
>  when you make a simple and functional project I will be happy

Ey I'm doing a lot of free work over here :(. 

Looks like you're still running on an old version of this repo. Please get the current one.

**Comment by cartergrobinson** [comment]
@Claudioappassionato you can also run `ollama pull all-minilm` on your Ollama server. This will download the model manually. Then, restart LLocalSearch and try again.
@nilsherzig thanks for you all your hard work. Loving this.

**Comment by Claudioappassionato** [comment]
> > quando realizzerai un progetto semplice e funzionale sarò felice
> 
> Ehi, sto facendo un sacco di lavoro gratis qui :(.
> 
> Sembra che tu stia ancora utilizzando una vecchia versione di questo repository. Per favore prendi quello attuale.

I'm actually using the one that's on display on the page
