### ISSUE TITLE
Can you give me the prompt for this?

### ISSUE THREAD

**Issue by psm227** [nilsherzig/LLocalSearch#41]
Can you give the prompt for the query generation and the response?

**Comment by nilsherzig** [comment]
Sorry i don't fully understand which prompt you're talking about

**Comment by psm227** [comment]
The system prompt?
How do you generate queries?
Do you tell Mistral something like this: Generate a query for this question...

**Comment by nilsherzig** [comment]
Ah yes, it's based on the go implementation of langchain: https://github.com/tmc/langchaingo

I would recommend running one of their example projects in debug mode to see all the queries and networking requests. But essentially its just prompting and if the LLM responds in a specified format the message isnt send to the user but handled by a program. This program will take the LLM message as an input and respond with something. (in this case a website's content for example). This response is then handled by the LLM.
