### ISSUE TITLE
Agent tool Repetive output

### ISSUE THREAD

**Issue by XiaoConstantine** [nilsherzig/LLocalSearch#53]
**Describe the bug**
When use `mistral:latest` as model, I get repetive output from agents, examples:
<img width="713" alt="Screenshot 2024-04-05 at 12 15 22 PM" src="https://github.com/nilsherzig/LLocalSearch/assets/3046977/c63b0f1b-b1df-4ebc-9bf5-6c8ec43a2ca4">

I didn't notice this behavior with `hermes-2-pro-mistral` tho

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nilsherzig** [comment]
I think this really comes down to fine-tuning prompts for each model. I already planned to make all internal prompts editable from the webinterface. Maybe we should add a warning next to "unsupported" models

How would you implement a short circuit? Just returning an error after n times the same response?

**Comment by XiaoConstantine** [comment]
Warning on unsupported models sounds good.

Regarding to short circuit, I think it probably should be done at agent level? e.g. plan? doesn't seems something caller can inject easily (correct me if i m wrong here)

**Comment by nilsherzig** [comment]
Yes this is something I would have to handle in the callback logic of each step. At the moment callbacks only push new logs to the Webinterface but I see no reason why they couldn't be used to short circuit something like that. 

A university professor of mine promised me access to more powerful hardware, which would allow me to implement and regularly run a test harness to catch things like this and develop solutions for them.

**Comment by XiaoConstantine** [comment]
Sounds good! Closing this for now
