### ISSUE TITLE
A message telling the user that the model is waking up.

### ISSUE THREAD

**Issue by dillfrescott** [nilsherzig/LLocalSearch#54]
Because ollama puts models to sleep (unloads them) after a few minutes of inactivity. It would be nice to show a message saying that the model is "waking up" or something to that extent.

**Comment by dillfrescott** [comment]
Also, I want to add youve made some significant improvements to the chat flow. looks 1000% better now damn.

**Comment by nilsherzig** [comment]
> Because ollama puts models to sleep (unloads them) after a few minutes of inactivity. It would be nice to show a message saying that the model is "waking up" or something to that extent.

yes this and a loading bar for pulling models the first time :). Im going to keep this issue open until I've implemented both

**Comment by dillfrescott** [comment]
Sounds good!

**Comment by nilsherzig** [comment]
> Also, I want to add youve made some significant improvements to the chat flow. looks 1000% better now damn.

thanks a lot :) i still need to implement a client side buffer for the whole "tool use messages gets turned into an icon" thing to avoid the flickering

**Comment by nilsherzig** [comment]
![image](https://github.com/nilsherzig/LLocalSearch/assets/72463901/15c96461-66d7-4328-bae5-964d495c47a8)

**Comment by dillfrescott** [comment]
Looks great!

**Comment by nilsherzig** [comment]
ay thanks :) its just a client side check tho

**Comment by nilsherzig** [comment]
![image](https://github.com/nilsherzig/LLocalSearch/assets/72463901/3d986b0f-b413-461f-81f2-59c8e4426c85)


now also works on model change in the same chat
