### ISSUE TITLE
The page bounces and glitches as the model types if the text box reaches the bottom of page.

### ISSUE THREAD

**Issue by dillfrescott** [nilsherzig/LLocalSearch#55]
Pretty much what the title says haha. Its glitchy as the model types and the whole page bounces up and down!

**Comment by nilsherzig** [comment]
its down to this mfer not linking the rapid changed while parsing markdown. 

https://github.com/nilsherzig/LLocalSearch/blob/1e19940ea5079fdd00e922bf7e7712f79eb9a47b/src/lib/log_item.svelte#L14

While using a slow model you can see how the markdown parser gets confused by the streaming text from time to time (for example everything becomes a heading while an empty list item exists). I think i need to implement some kind of buffer for this. I still want the streaming responses be in rendered markdown. Especially tables look very cool while getting created haha

**Comment by dillfrescott** [comment]
Ohhhhh gotcha!

> I still want the streaming responses be in rendered markdown. 

Yes certainly! I think it's really cool too!

**Comment by nilsherzig** [comment]
i really dont know how to fix the glitching, so i guess i should just debounce the page scrolling?

**Comment by dillfrescott** [comment]
Thats fine!

**Comment by nilsherzig** [comment]
nvm i think i got it
