### ISSUE TITLE
"Stop Generating" button

### ISSUE THREAD

**Issue by dillfrescott** [nilsherzig/LLocalSearch#57]

**Comment by nilsherzig** [comment]
Not really happy with having everything in one button, but i have to get some sleep before writing more code haha

**Comment by nilsherzig** [comment]
![image](https://github.com/nilsherzig/LLocalSearch/assets/72463901/07f3c12f-7d9d-430b-9440-57096804bba4)
![image](https://github.com/nilsherzig/LLocalSearch/assets/72463901/c6c2cf15-c870-4aca-b162-b6bd2e9fbe0d)
![image](https://github.com/nilsherzig/LLocalSearch/assets/72463901/7641c867-706c-4d24-ab13-829e9aae335f)

**Comment by dillfrescott** [comment]
> Not really happy with having everything in one button, but i have to get some sleep before writing more code haha

no problem! also that looks good!
