### ISSUE TITLE
Embedding model shouldn't show up in the list of available models

### ISSUE THREAD

**Issue by dillfrescott** [nilsherzig/LLocalSearch#59]

**Comment by nilsherzig** [comment]
Yes but there is no way to filter them, the ollama API doesn't have a way to distinguish them

**Comment by dillfrescott** [comment]
Ohhh okay that makes sense

**Comment by nilsherzig** [comment]
i can filter the currently used embeddings model

**Comment by nilsherzig** [comment]
better than nothing i guess haha

**Comment by dillfrescott** [comment]
I was thinking about mentioning that as a possible solution haha
