### ISSUE TITLE
Get "https://registry-1.docker.io/v2/": read tcp 192.168.1.198:55070->54.227.20.253:443: read: connection reset by peer

### ISSUE THREAD

**Issue by PieBru** [nilsherzig/LLocalSearch#6]
Hi, I'm installing using `make dev` on my Arch Linux box.

Is this an authentication error?

```log
(LLocalsearch) 19:45:18 piero@gl753vd  LLocalsearch $ make dev
docker-compose -f ./docker-compose.dev.yaml build
[+] Building 1.3s (13/13) FINISHED                                                                                                                            docker:default
 => [backend-dev internal] load build definition from Dockerfile.dev                                                                                                    0.0s
 => => transferring dockerfile: 149B                                                                                                                                    0.0s
 => [backend-dev internal] load metadata for docker.io/library/golang:alpine3.19                                                                                        0.5s
 => [backend-dev internal] load .dockerignore                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                         0.0s
 => [backend-dev 1/3] FROM docker.io/library/golang:alpine3.19@sha256:0466223b8544fb7d4ff04748acc4d75a608234bf4e79563bff208d2060c0dd79                                  0.0s
 => CACHED [backend-dev 2/3] WORKDIR /app                                                                                                                               0.0s
 => CACHED [backend-dev 3/3] RUN go install github.com/cosmtrek/air@latest                                                                                              0.0s
 => [backend-dev] exporting to image                                                                                                                                    0.0s
 => => exporting layers                                                                                                                                                 0.0s
 => => writing image sha256:082259fe1045e35be0d8337ae5126406ed4d0f74403bc59e581d39536df22120                                                                            0.0s
 => => naming to docker.io/library/llocalsearch-backend-dev                                                                                                             0.0s
 => [frontend-dev internal] load build definition from Dockerfile.dev                                                                                                   0.0s
 => => transferring dockerfile: 148B                                                                                                                                    0.0s
 => [frontend-dev internal] load metadata for docker.io/library/node:20-alpine3.19                                                                                      0.6s
 => [frontend-dev internal] load .dockerignore                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                         0.0s
 => [frontend-dev 1/2] FROM docker.io/library/node:20-alpine3.19@sha256:ef3f47741e161900ddd07addcaca7e76534a9205e4cd73b2ed091ba339004a75                                0.0s
 => CACHED [frontend-dev 2/2] WORKDIR /app                                                                                                                              0.0s
 => [frontend-dev] exporting to image                                                                                                                                   0.0s
 => => exporting layers                                                                                                                                                 0.0s
 => => writing image sha256:eee1d3e3951d679fe05a6f47a218d743e4050b39cb8567d75fa2b8e8eebecd79                                                                            0.0s
 => => naming to docker.io/library/llocalsearch-frontend-dev                                                                                                            0.0s
docker-compose -f ./docker-compose.dev.yaml up
[+] Running 3/3
 ✘ searxng Error  context canceled                                                                                                                                      0.4s 
 ✘ chromadb Error context canceled                                                                                                                                      0.4s 
 ✘ redis Error    Get "https://registry-1.docker.io/v2/": read tcp 192.168.1.198:55070->54.227.20.253:443: read: connection reset by peer                               0.4s 
Error response from daemon: Get "https://registry-1.docker.io/v2/": read tcp 192.168.1.198:55070->54.227.20.253:443: read: connection reset by peer
make: *** [Makefile:7: dev] Error 18
```

Thank you,
Piero

**Comment by nilsherzig** [comment]
The "make dev" command builds all of my code from source and pulls some other openly available docker containers. Nothing should require authentication beyond the default TLS stuff. My guess is that your network blocks or is blocked by the docker registry. Please try pulling a random docker container and check if that works. For example "docker pull ubuntu" :)

**Comment by PieBru** [comment]
Thank you for your reply, I suspected it was - and probably is - a problem on my side, but here all seems fine, `docker pull` included.
What can I try?

```log
(base) 21:27:09 piero@gl753vd  LLocalsearch $ sudo docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
c1ec31eb5944: Pull complete 
Digest: sha256:53641cd209a4fecfc68e21a99871ce8c6920b2e7502df0a20671c6fccc73a7c6
Status: Downloaded newer image for hello-world:latest
docker.io/library/hello-world:latest
```

**Comment by PieBru** [comment]
Confirmed by the browser... but it's definitely on my side.
https://forums.docker.com/t/docker-hub-unable-to-pull-container-connection-reset-by-peer/140303

![image](https://github.com/nilsherzig/LLocalSearch/assets/6537434/c86e3b64-1cc5-4e1b-804d-a48b01e021e4)

**Comment by nilsherzig** [comment]
I only have my phone with me at the moment, so it's kinda hard to debug things, but according to your logs above searxng, redis and chroma failed while the docker build commands (which pull alpine images) worked. 

Could you please run "docker pull docker.io/library/redis:alpine" for me? That's the redis container which failed to pull via make. 

![Screenshot_20240330-221050.png](https://github.com/nilsherzig/LLocalSearch/assets/72463901/8bc354b9-87f1-4991-8eb5-ff14fcb7d5f6)

Here is a cursed screenshot of a ssh session on my phone running the command

**Comment by nilsherzig** [comment]
> Confirmed by the browser... but it's definitely on my side.
> https://forums.docker.com/t/docker-hub-unable-to-pull-container-connection-reset-by-peer/140303
> 
> ![image](https://github.com/nilsherzig/LLocalSearch/assets/6537434/c86e3b64-1cc5-4e1b-804d-a48b01e021e4)
> 

Btw I think the auth error while visiting the web root is normal ![Screenshot_20240330-221424.png](https://github.com/nilsherzig/LLocalSearch/assets/72463901/5e5b4a8c-cd09-4867-ab7a-da0a51a078ea)

**Comment by nilsherzig** [comment]
![Screenshot_20240330-221640.png](https://github.com/nilsherzig/LLocalSearch/assets/72463901/b9766b28-bfa1-4d6e-a093-a069c17d9714)

Pull works from the same server, so that definitely isn't the issue

**Comment by PieBru** [comment]
`docker pull` works, but the `make dev` error persists:
```log
(LLocalsearch) 09:57:14 piero@gl753vd  LLocalsearch $ git branch
* main
(LLocalsearch) 09:57:25 piero@gl753vd  LLocalsearch $ git pull
Already up to date.
(LLocalsearch) 09:57:32 piero@gl753vd  LLocalsearch $ make dev
docker-compose -f ./docker-compose.dev.yaml build
[+] Building 2.7s (13/13) FINISHED                                                                                                                            docker:default
 => [backend-dev internal] load build definition from Dockerfile.dev                                                                                                    0.0s
 => => transferring dockerfile: 149B                                                                                                                                    0.0s
 => [backend-dev internal] load metadata for docker.io/library/golang:alpine3.19                                                                                        1.4s
 => [backend-dev internal] load .dockerignore                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                         0.0s
 => [backend-dev 1/3] FROM docker.io/library/golang:alpine3.19@sha256:0466223b8544fb7d4ff04748acc4d75a608234bf4e79563bff208d2060c0dd79                                  0.0s
 => CACHED [backend-dev 2/3] WORKDIR /app                                                                                                                               0.0s
 => CACHED [backend-dev 3/3] RUN go install github.com/cosmtrek/air@latest                                                                                              0.0s
 => [backend-dev] exporting to image                                                                                                                                    0.0s
 => => exporting layers                                                                                                                                                 0.0s
 => => writing image sha256:082259fe1045e35be0d8337ae5126406ed4d0f74403bc59e581d39536df22120                                                                            0.0s
 => => naming to docker.io/library/llocalsearch-backend-dev                                                                                                             0.0s
 => [frontend-dev internal] load build definition from Dockerfile.dev                                                                                                   0.0s
 => => transferring dockerfile: 148B                                                                                                                                    0.0s
 => [frontend-dev internal] load metadata for docker.io/library/node:20-alpine3.19                                                                                      1.1s
 => [frontend-dev internal] load .dockerignore                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                         0.0s
 => [frontend-dev 1/2] FROM docker.io/library/node:20-alpine3.19@sha256:ef3f47741e161900ddd07addcaca7e76534a9205e4cd73b2ed091ba339004a75                                0.0s
 => CACHED [frontend-dev 2/2] WORKDIR /app                                                                                                                              0.0s
 => [frontend-dev] exporting to image                                                                                                                                   0.0s
 => => exporting layers                                                                                                                                                 0.0s
 => => writing image sha256:eee1d3e3951d679fe05a6f47a218d743e4050b39cb8567d75fa2b8e8eebecd79                                                                            0.0s
 => => naming to docker.io/library/llocalsearch-frontend-dev                                                                                                            0.0s
docker-compose -f ./docker-compose.dev.yaml up
[+] Running 2/2
 ✘ searxng Error  Head "https://registry-1.docker.io/v2/searxng/searxng/manifests/latest": read tcp 192.168.1.198:41226->54.198.86.24:443: read: conn...                1.2s 
 ✘ chromadb Error context canceled                                                                                                                                      1.2s 
Error response from daemon: Head "https://registry-1.docker.io/v2/searxng/searxng/manifests/latest": read tcp 192.168.1.198:41226->54.198.86.24:443: read: connection reset by peer
make: *** [Makefile:7: dev] Error 18
(LLocalsearch) 09:57:45 piero@gl753vd  LLocalsearch $ docker pull docker.io/library/redis:alpine
alpine: Pulling from library/redis
4abcf2066143: Already exists 
5c3180d10209: Pull complete 
f76326fd8e6b: Pull complete 
034c076ba1e7: Pull complete 
dffcad17539b: Pull complete 
5913474e0f39: Pull complete 
4f4fb700ef54: Pull complete 
cc6fccbbefa3: Pull complete 
Digest: sha256:7635b0bfdd7dd8552b4b31d6541fef07b734614045b45a52fd5cc27c9dada9e2
Status: Downloaded newer image for redis:alpine
docker.io/library/redis:alpine
(LLocalsearch) 10:00:51 piero@gl753vd  LLocalsearch $ 
```

**Comment by PieBru** [comment]
As the error happens while executing `docker-compose` I reviewed it but nothing changed.
```bash
(LLocalsearch) 10:07:37 piero@gl753vd  LLocalsearch $ docker compose -f ./docker-compose.dev.yaml up
[+] Running 2/2
 ✘ chromadb Error context canceled                                                                                                                                      1.0s 
 ✘ searxng Error  Head "https://registry-1.docker.io/v2/searxng/searxng/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Asearx...                1.0s 
Error response from daemon: Head "https://registry-1.docker.io/v2/searxng/searxng/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Asearxng%2Fsearxng%3Apull&service=registry.docker.io": read tcp 192.168.1.198:38908->54.227.20.253:443: read: connection reset by peer
```

**Comment by PieBru** [comment]
BTW, I suggest to put `127.0.0.1` as the default Ollama IP in the compose file, as it's the most common default.

**Comment by PieBru** [comment]
It looks weird to me.

The `HTTPS Get` of the token suceeds, but the registry requires auth:
```bash
(LLocalsearch) 10:15:21 piero@gl753vd  LLocalsearch $ curl "https://auth.docker.io/token?scope=repository%3Asearxng%2Fsearxng%3Apull&service=registry.docker.io" -s | jq
{
  "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlFRmpDQ0F2NmdBd0lCQWdJVVZOajJRbU1JWnUzeGl0NUJ1RTlvRW...
  MPlAH_Mnz9PQTbWATO0FMA4zISuOwo6Anai806_z1pw",
  "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlFRmpDQ0F2NmdBd0lCQWdJVVZOajJRbU1JWnUzeGl0NUJ1RTlvRW...
  MPlAH_Mnz9PQTbWATO0FMA4zISuOwo6Anai806_z1pw",
  "expires_in": 300,
  "issued_at": "2024-03-31T08:15:34.258816191Z"
}
(LLocalsearch) 10:15:34 piero@gl753vd  LLocalsearch $ curl "https://registry-1.docker.io/v2/searxng/searxng/manifests/latest" -s | jq
{
  "errors": [
    {
      "code": "UNAUTHORIZED",
      "message": "authentication required",
      "detail": [
        {
          "Type": "repository",
          "Class": "",
          "Name": "searxng/searxng",
          "Action": "pull"
        }
      ]
    }
  ]
}
```

**Comment by PieBru** [comment]
Got it!
The `OPENAI_API_KEY` *must* contain some value even when using Ollama which doesn't need it, otherwise some library complains.

In `docker-compose-dev.yaml` set:
```
OPENAI_API_KEY=not-needed
```

So:
```bash
(LLocalsearch) 10:37:58 piero@gl753vd  LLocalsearch $ docker-compose -f ./docker-compose.dev.yaml up
[+] Running 2/4
 ✔ Container redis                        Running                                                                                                                       0.0s 
 ✔ Container llocalsearch-chromadb-1      Running                                                                                                                       0.0s 
 ⠴ Container llocalsearch-backend-dev-1   Recreated                                                                                                                     0.5s 
 ⠋ Container llocalsearch-frontend-dev-1  Recreated                                                                                                                     0.0s 
Attaching to backend-dev-1, chromadb-1, frontend-dev-1, redis, searxng
backend-dev-1   | 
backend-dev-1   |   __    _   ___  
backend-dev-1   |  / /\  | | | |_) 
backend-dev-1   | /_/--\ |_| |_| \_ v1.51.0, built with Go go1.22.1
backend-dev-1   | 
```

**Comment by nilsherzig** [comment]
Ohhh I think I know why, sorry for wasting your time with this :/ and thanks for reporting, will fix this asap

**Comment by nilsherzig** [comment]
> BTW, I suggest to put `127.0.0.1` as the default Ollama IP in the compose file, as it's the most common default.

Wouldn't this require the docker to run as net=host? Since localhost inside the container isn't localhost of the host

**Comment by nilsherzig** [comment]
> Got it! The `OPENAI_API_KEY` _must_ contain some value even when using Ollama which doesn't need it, otherwise some library complains.
> 
> In `docker-compose-dev.yaml` set:
> 
> ```
> OPENAI_API_KEY=not-needed
> ```
> 
> So:
> 
> ```shell
> (LLocalsearch) 10:37:58 piero@gl753vd  LLocalsearch $ docker-compose -f ./docker-compose.dev.yaml up
> [+] Running 2/4
>  ✔ Container redis                        Running                                                                                                                       0.0s 
>  ✔ Container llocalsearch-chromadb-1      Running                                                                                                                       0.0s 
>  ⠴ Container llocalsearch-backend-dev-1   Recreated                                                                                                                     0.5s 
>  ⠋ Container llocalsearch-frontend-dev-1  Recreated                                                                                                                     0.0s 
> Attaching to backend-dev-1, chromadb-1, frontend-dev-1, redis, searxng
> backend-dev-1   | 
> backend-dev-1   |   __    _   ___  
> backend-dev-1   |  / /\  | | | |_) 
> backend-dev-1   | /_/--\ |_| |_| \_ v1.51.0, built with Go go1.22.1
> backend-dev-1   | 
> ```

i wasnt able to reprodue this at my end. I tried:
- cleaning my hosts openai env var
- providing a blank env var in the compose file
- providing no env var in the compose file

But since this project is supposed to run without any of the big players anyway, I still removed the OpenAI code from the repo.

**Comment by PieBru** [comment]
> i wasnt able to reprodue this at my end. I tried:
    cleaning my hosts openai env var
    providing a blank env var in the compose file
    providing no env var in the compose file

It's not the first time I encounter this issue. AFAIK also Ollama, LangChain and others falled in this trap, i.e. https://github.com/ollama/ollama/issues/305#issuecomment-1862640502
This is why I tried it and without other changes I passed the previous critical point.
BTW my previous log is truncated as my port 8080 is already occupied., thus the other issue.

**Comment by PieBru** [comment]
> > BTW, I suggest to put `127.0.0.1` as the default Ollama IP in the compose file, as it's the most common default.
> 
> Wouldn't this require the docker to run as net=host? Since localhost inside the container isn't localhost of the host. Also, I think this just isn't an option for Windows users, since containers run inside a vm on Windows.

This is my Open-WebUI run command that works with `--network=host` and `http://127.0.0.1:11434/`:
```bash
docker container run -d --network=host -v open-webui:/app/backend/data -e OLLAMA_API_BASE_URL=http://127.0.0.1:11434/api --name open-webui --restart always ghcr.io/ope>
```

You had a very nice idea with this app!
Piero

**Comment by PieBru** [comment]
I confirm it works here, and your concept is awesomely useful for real tasks!

Asking to search and create a summary of all 10 best publications on the medical domain that have some common characteristics in the related clinical trial, your "agent" after a single *automagic* query gave better results than multiple manual queries with Bing_dev with GPT4.

Keep it going on!
Cheers,
Piero

**Comment by nilsherzig** [comment]
> > > BTW, I suggest to put `127.0.0.1` as the default Ollama IP in the compose file, as it's the most common default.
> > 
> > 
> > Wouldn't this require the docker to run as net=host? Since localhost inside the container isn't localhost of the host. Also, I think this just isn't an option for Windows users, since containers run inside a vm on Windows.
> 
> This is my Open-WebUI run command that works with `--network=host` and `http://127.0.0.1:11434/`:
> 
> ```shell
> docker container run -d --network=host -v open-webui:/app/backend/data -e OLLAMA_API_BASE_URL=http://127.0.0.1:11434/api --name open-webui --restart always ghcr.io/ope>
> ```
> 
> You had a very nice idea with this app! Piero

Appreciate the kind words :)

The problem with this attempt is, that the containers currently communicate over a private network interface (called llm_network_dev) which is in my opinion a very clean way to let them talk with each other without interfering with any existing networking (it also provides dns for the container names etc). Using net=host on one of the containers stops the container from being able to join these networks. I think this https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container might be a good solution for a default value :)

**Comment by nilsherzig** [comment]
> I confirm it works here, and your concept is awesomely useful for real tasks!
> 
> Asking to search and create a summary of all 10 best publications on the medical domain that have some common characteristics in the related clinical trial, your "agent" after a single _automagic_ query gave better results than multiple manual queries with Bing_dev with GPT4.
> 
> Keep it going on! Cheers, Piero

uhh thats nice :)

I got very different results (quality vise) with different models and some internal settings. I'm going to expose all of them to the interface in the next couple of days :)

**Comment by PieBru** [comment]
> The problem with this attempt is, that the containers currently communicate over a private network interface (called llm_network_dev) which is in my opinion a very clean way to let them talk with each other without interfering with any existing networking (it also provides dns for the container names etc). Using net=host on one of the containers stops the container from being able to join these networks. I think this https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container might be a good solution for a default value :)

I prefer your way, it's is cleaner. But it's my opinion, others may prefer an egg today more than a chicken the next month :)

From the perspective of a newcomer, IMO it's important that following the documentation the installation and 1st run proceed smoothly. As you said, the docker container is a better solution than dealing with the dev/build environment.

**Comment by nilsherzig** [comment]
> > The problem with this attempt is, that the containers currently communicate over a private network interface (called llm_network_dev) which is in my opinion a very clean way to let them talk with each other without interfering with any existing networking (it also provides dns for the container names etc). Using net=host on one of the containers stops the container from being able to join these networks. I think this https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container might be a good solution for a default value :)
> 
> I prefer your way, it's is cleaner. But it's my opinion, others may prefer an egg today more than a chicken the next month :)
> 
> From the perspective of a newcomer, IMO it's important that following the documentation the installation and 1st run proceed smoothly. As you said, the docker container is a better solution than dealing with the dev/build environment.

Yea, you're right about that. I plan to add a working ci / a somewhat solid alpha release before adding more features. By spending some time on cleaning everything up, I can save a lot of time for other people haha :)
