### ISSUE TITLE
error connecting to the searxng container

### ISSUE THREAD

**Issue by toothytoad** [nilsherzig/LLocalSearch#62]
**Describe the bug**
When I run a search it errors when trying to connect to the searxng container.

**To Reproduce**
1. git clone https://github.com/nilsherzig/LLocalSearch
2. podman-compose up
3. navigate to http://localhost:3000/ in the browser
4. click a default search

**Expected behavior**
Connect to the searxng container and get search results

**Console**

```
2024/04/05 21:46:37 Error making the request: Get "http://searxng:8080/?q=average+weight+of+a+llama&format=json": dial tcp 10.89.5.62:8080: i/o timeout
[backend]  | Exiting chain with error: Get "http://searxng:8080/?q=average+weight+of+a+llama&format=json": dial tcp 10.89.5.62:8080: i/o timeout
```

**Additional context**
 I'm on the most recent changes ie I just did a git pull and podman-compose pull
 
 Thank you for the help

**Comment by nilsherzig** [comment]
can you confirm the same behavoir using docker-compose? Im happy to support podman, but i haven't tested it myself and someone is working on podman i think #37

**Comment by toothytoad** [comment]
Thank you for responding.  Both podman and docker are connecting to searxng now, I'm not sure what changed. However both have the same new error, but someone seems to have filed a bug for that at #50. I'll close this issue.
