### ISSUE TITLE
Wonky input box on mobile

### ISSUE THREAD

**Issue by dillfrescott** [nilsherzig/LLocalSearch#63]
![Screenshot_20240405_182353_Edge](https://github.com/nilsherzig/LLocalSearch/assets/56714680/fada5406-8f39-446f-802a-5212b021e10e)

**Comment by nilsherzig** [comment]
I can't reproduce this issue on chrome / firefox on my pixel 7 or using mobile view on my desktop. Might be a Samsung browser issue?

**Comment by dillfrescott** [comment]
Let me try the latest commit and I'll see if it's still doing it.

I'll do it in a bit with my phone.
