### ISSUE TITLE
Could Not Pull Model

### ISSUE THREAD

**Issue by MagFlux** [nilsherzig/LLocalSearch#64]
**Describe the bug**
Upon cloning the repo (commit 0b695f3eff6a8595631eabb2b64b8598f5cc43ed) and running the docker container I get to the hosted web page and upon issuing any queries I get the following error on the web page:
`Model nomic-embed-text:v1.5 does not exist and could not be pulled: Post "http://host.docker.internal:11434/api/pull": dial tcp 172.17.0.1:11434: connect: connection refused`
and the following show on the console output:
`llocalsearch-backend-1   | 2024/04/06 02:33:05 WARN Model does not exist, pulling it model=nomic-embed-text:v1.5
llocalsearch-backend-1   | 2024/04/06 02:33:05 ERROR Model does not exist and could not be pulled model=nomic-embed-text:v1.5 error="Post \"http://host.docker.internal:11434/api/pull\": dial tcp 172.17.0.1:11434: connect: connection refused"`

**To Reproduce**
1. Go to the web front end @ http://localhost:3000/ after cloning the repo and running docker-compose up
2. Click on any of the recommended queries or enter your own and hit enter
3. See error displayed on the webpage and the error shown on the console from where the container was spooled up.

**Expected behavior**
Expect the query to be responded to.

**Screenshots**
N/A

**Additional context**
Tried switching to the tag v0.1 and had same issue but with different output.
Web page showed:
`Model nomic-embed-text:v1.5 does not exist and could not be pulled: Post "http://192.168.0.109:11434/api/pull": dial tcp 192.168.0.109:11434: connect: no route to host`
Console showed:
`llocalsearch-backend-1   | 2024/04/06 02:46:12 WARN Model does not exist, pulling it model=nomic-embed-text:v1.5
llocalsearch-backend-1   | 2024/04/06 02:46:15 ERROR Model does not exist and could not be pulled model=nomic-embed-text:v1.5 error="Post \"http://192.168.0.109:11434/api/pull\": dial tcp 192.168.0.109:11434: connect: no route to host"`

**Comment by nilsherzig** [comment]
Looks like the backend isn't able to connect to ollama. Can you show me your ollama start command, maybe it's not listening on the right interface?

**Comment by MagFlux** [comment]
OH! I apologize...I just saw the requirements portion of the readme (DO'H) stating "A running [Ollama](https://ollama.com/) server, reachable from the container". Sorry about that, I'm sure this is the issue. I'll give a shot at running this and will report back.

**Comment by MagFlux** [comment]
Yep that was it...wasn't running the Ollama server. Thanks again for your help...closing issue.

**Comment by nilsherzig** [comment]
No problem :). I know the setup process isn't there yet. Im working on a couple of tutorials especially for the whole ollama and networking part :)

**Comment by fbaew** [comment]
Commenting here because I'm seeing a very similar issue, though not exactly the same!

My Ollama server is reachable from the Llocalsearch backend container:

```
~ # env
HOSTNAME=1654d00d8c40
SHLVL=1
HOME=/root
OLLAMA_HOST=http://host.docker.internal:11434
CHROMA_DB_URL=http://chromadb:8000
TERM=xterm
SEARXNG_DOMAIN=http://searxng:8080
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MAX_ITERATIONS=30
PWD=/root
~ # nc host.docker.internal 11434
GET / HTTP/1.1
Host: host.docker.internal

HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Date: Sat, 20 Apr 2024 01:08:07 GMT
Content-Length: 17

Ollama is running
```

As you can infer from above, I also updated the docker-compose config to set the OLLAMA_HOST envvar. When I visit the webui, the model I have installed in Ollama (Llama3) is shown in the settings dialog! However, when I select it from the dropdown, close the modal, and try to make a query, I am greeted with an error:

> Model does not exist and could not be pulled: model is required. 

The error console for the backend container gives a little hint:

```
backend-1   | 2024/04/20 01:10:04 WARN Model does not exist, pulling it model=""
backend-1   | 2024/04/20 01:10:04 ERROR Model does not exist and could not be pulled model="" error="model is required"
```

So to me it looks like no model name is getting passed when I select the model in the frontend. Am I missing a config step here? I'm doing this on Windows 10 (God help me!)

Let me know if I can provide more useful information; in the meantime I'll continue investigating on my own.

**Comment by fbaew** [comment]
Following up since this is (for my purposes) resolved...

I tried using docker-compose.dev.yaml instead of docker-compose.yaml, and everything worked properly!
