### ISSUE TITLE
feat: stateful chats

### ISSUE THREAD

**Issue by nilsherzig** [nilsherzig/LLocalSearch#7]
Allow users to ask follow-up questions

**Comment by dillfrescott** [comment]
Yes! Was going to ask for this!

**Comment by nilsherzig** [comment]
> Yes! Was going to ask for this!

I got them working, but still need some time testing some parameters, since the models behave different if they run in "ConversationalReactDescription" Mode

**Comment by nilsherzig** [comment]
![image](https://github.com/nilsherzig/LLocalSearch/assets/72463901/2d7ac52c-dff5-4fb6-9b7c-ffcdc485652e)

yea yea (obv still needs a better UI) and I'm going to add a history of recent chats (like OpenAI does) 

dont ask me about the calculator move tho haha

**Comment by dillfrescott** [comment]
A way to save or share chats directly would be cool too

**Comment by nilsherzig** [comment]
> A way to save or share chats directly would be cool too

Yes, that's fairly easy to do, since the whole thing is just a map between an uuid and a memory object.

Basically, you're sending the UUID with your prompt and the backend will associate this ID with an existing memory object, or create a new one. The map is only in memory at the moment. Which means that chats don't survive a server restart. I think I will add a simple sqlite3 db to make this persistent. After that, the browser just has to remember used UUIDs and can request the chats histories from the server. 

This is far from optimal in terms of security, but would be easy to extend with some kind of middleware in the future.
