### ISSUE TITLE
You may need to add a version declaration to the 'docker-compose.yaml' file

### ISSUE THREAD

**Issue by kamjin1996** [nilsherzig/LLocalSearch#79]
**Describe the bug**
I follow the steps to pull the code, and after I run docker-compose up directly, I get the following message: ERROR: Invalid interpolation format for "backend" option in service "services": "OLLAMA_HOST=${OLLAMA_HOST:-http://host.docker.internal:11434}"

**To Reproduce**
1. Pull the code 
2. Enter the pulled folder 
3. Run docker-compose up

**Expected behavior**
The docker-compose syntax error due to no declared version will no longer be prompted.

**Screenshots**

**Additional context**
Just add the following at the top of docker-compose.yaml: 
`version: "3.7"`
He should be working normally at this point.

**Comment by nilsherzig** [comment]
Oh thanks for pointing that out. I'm currently building an end to end test pipeline for the whole projekt. 

My tests VMs are NixOS unstable and Ubuntu 22.04 and I didn't catch this error. Which OS and docker-compose version are you on? 

Btw I thinking docker-compose is getting deprecated for "docker compose" which doesn't need the version Tag

**Comment by Technetium1** [comment]
Compose version 1 has been deprecated since June 2023, so there is no longer a need to specify version. If `version` is specified, it results in a warning.

The latest schema will always prefer the latest version: https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements

**Comment by nilsherzig** [comment]
@Technetium1 i think a lot of people are running very old systems. Someone in another issue was running docker-compose from 9 years go
