### ISSUE TITLE
[Feature] Make it easier or document how to change the default port from 8080

### ISSUE THREAD

**Issue by PieBru** [nilsherzig/LLocalSearch#8]
Hi, port 8080 is quite common, and chances are it's used by other servers or WebUI.

Changing it in the `docker-compose-dev.yaml` isn't enough, because it's also hard-coded in other files, such as:
```bash
(LLocalsearch) 10:50:43 piero@gl753vd  LLocalsearch $ grep -R 8080 *
backend/Dockerfile.dev:EXPOSE 8080
backend/apiServer.go:	fmt.Println("Server started at http://localhost:8080")
backend/apiServer.go:	http.ListenAndServe(":8080", nil)
backend/Dockerfile:# Expose port 8080 to the outside world
backend/Dockerfile:EXPOSE 8080
grep: backend/tmp/main: binary file matches
docker-compose.dev.yaml:      - '8080:8080'
node_modules/vite/dist/node/index.d.ts:     * @example `http://127.0.0.1:8080`
node_modules/sade/readme.md:  .example('--port 8080 --etag')
node_modules/sade/readme.md:    $ sirv --port 8080 --etag
vite.config.ts:                target: 'http://backend-dev:8080',
...
```

Thank you,
Piero

**Comment by nilsherzig** [comment]
Ah you're right, I missed that. Exposing the backend is no longer needed anyways. The frontend proxies request to /api to the backend (see vite config). Will remove this :)

**Comment by nilsherzig** [comment]
I think I should really add a GitHub ci action to build proper containers and not let people build the project from source

**Comment by nilsherzig** [comment]
Looks like it wasn't my backend that was exposed, but the searXNG container. Fixed that :)

Now only the frontend port (3000) should be exposed, changing that one should work via the docker-compose file
