### ISSUE TITLE
Fontend missing file

### ISSUE THREAD

**Issue by Arbow** [nilsherzig/LLocalSearch#80]
**Describe the bug**
Using docker compose to start containers, then container llocalsearch-frontend-1 found error logs:

<img width="857" alt="image" src="https://github.com/nilsherzig/LLocalSearch/assets/14039/b6048dd4-8b81-4bb4-b1c2-e84f78972563">

**Comment by nilsherzig** [comment]
Which browser are you using? serviceWorker.js is a file used to create progressive web apps, but my frontend isn't a progressive web app, haha. I assume your browser tries to load this file for some reason / by default

**Comment by Arbow** [comment]
> Which browser are you using? serviceWorker.js is a file used to create progressive web apps, but my frontend isn't a progressive web app, haha. I assume your browser tries to load this file for some reason / by default

I am using Arc browser

**Comment by nilsherzig** [comment]
Can you confirm that this error does not exist when using another browser? If I remember correctly, arc is MacOS only and I don't have an apple device
