### ISSUE TITLE
Error/warning on Apple Silicon

### ISSUE THREAD

**Issue by arsaboo** [nilsherzig/LLocalSearch#87]
I am seeing the following on my terminal when I run the container:

```! frontend The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s```

Everything is working, but I guess it is due to a platform mismatch and this warning/error could be gracefully handled.

**Comment by nilsherzig** [comment]
oh good point, i should also build containers for arm, thanks :)

**Comment by nilsherzig** [comment]
closing for #90
